package cn.wqp.crm;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.wqp.cn/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomersToDecidedZone", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.AssignCustomersToDecidedZone")
    @ResponseWrapper(localName = "assignCustomersToDecidedZoneResponse", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.AssignCustomersToDecidedZoneResponse")
    public void assignCustomersToDecidedZone(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.wqp.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findhasassociationCustomers", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindhasassociationCustomers")
    @ResponseWrapper(localName = "findhasassociationCustomersResponse", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindhasassociationCustomersResponse")
    public List<Customer> findhasassociationCustomers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.wqp.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findnoassociationCustomers", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindnoassociationCustomers")
    @ResponseWrapper(localName = "findnoassociationCustomersResponse", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindnoassociationCustomersResponse")
    public List<Customer> findnoassociationCustomers();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.wqp.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByPickaddress", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindDecidedzoneIdByPickaddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByPickaddressResponse", targetNamespace = "http://service.crm.wqp.cn/", className = "cn.wqp.crm.service.FindDecidedzoneIdByPickaddressResponse")
    public String findDecidedzoneIdByPickaddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
